;-------Show Erase File dialog
CODE_00B1CE:        REP   #$30                ;
                    LDA.w $0218               ;
                    AND.w #$0003              ;
                    ASL   A                   ;
                    TAY                       ;
                    PHY                       ;
                    LDA.w $0221               ;
                    AND.w #$000F              ;
                    XBA                       ;
                    LSR   A                   ;
                    LSR   A                   ;
                    LSR   A                   ;
                    STA.b $0E                 ;
                    TAX                       ;
                    LDA.w DATA_00B34A,y       ;
                    SEC                       ;
                    SBC.b $0E                 ;
                    STA.b $00                 ;
                    LDA.w DATA_00B34A+$10,y   ;
                    STA.b $02                 ;
                    LDA.w $0221               ;
                    AND.w #$000F              ;
                    ASL   A                   ;
                    TAY                       ;
                    LDA.w DATA_00B34A+$20,y   ;
                    STA.b $08                 ;
                    STZ.b $04                 ;
                    LDA.l $7F8000             ;
                    TAX                       ;
                    JSR.w CODE_00B27C         ;
                    PLY                       ;
                    BEQ   +                   ;
                    CPY.w #$0004              ;
                    BEQ   +                   ;
                    LDA.b $00                 ;
                    AND.w #$7FE0              ;
                    EOR.w #$0400              ;
                    STA.b $00                 ;
                    LDA.w DATA_00B34A+$18,y   ;
                    STA.b $02                 ;
                    JSR.w CODE_00B27C         ;
+                   PHY                       ;
                    LDA.w DATA_00B34A+8,y     ;
                    CLC                       ;
                    ADC.b $0E                 ;
                    STA.b $00                 ;
                    LDA.w DATA_00B34A+$10,y   ;
                    STA.b $02                 ;
                    LDA.w $0221               ;
                    AND.w #$000F              ;
                    ASL   A                   ;
                    TAY                       ;
                    LDA.w DATA_00B34A+$28,y   ;
                    STA.b $08                 ;
                    STZ.b $04                 ;
                    JSR.w CODE_00B27C         ;
                    PLY                       ;
                    BEQ   +                   ;
                    CPY.w #$0004              ;
                    BEQ   +                   ;
                    LDA.b $00                 ;
                    AND.w #$7FE0              ;
                    EOR.w #$0400              ;
                    STA.b $00                 ;
                    LDA.w DATA_00B34A+$18,y   ;
                    STA.b $02                 ;
                    JSR.w CODE_00B27C         ;
+                   LDA.w #$FFFF              ;
                    STA.l $7F8002,x           ;
                    TXA                       ;
                    STA.l $7F8000             ;
                    SEP   #$30                ;
                    INC.w $0221               ;
                    LDA.w $0221               ;
                    CMP.b #$04                ;
                    BNE   .end                ;
                    INC.b $E0                 ;
                    STZ.w $0222               ;
.end                RTL                       ;

CODE_00B27C:        PHY                       ;
                    LDA.b $00                 ;
                    XBA                       ;
                    STA.l $7F8002,x           ;
                    INX                       ;
                    INX                       ;
                    LDA.b $02                 ;
                    XBA                       ;
                    STA.l $7F8002,x           ;
                    INX                       ;
                    INX                       ;
                    LSR.b $02                 ;
                    LDY.b $04                 ;
-                   LDA.b ($08),y             ;
                    STA.l $7F8002,x           ;
                    INX                       ;
                    INX                       ;
                    INY                       ;
                    INY                       ;
                    DEC.b $02                 ;
                    BNE   -                   ;
                    STY.b $04                 ;
                    PLY                       ;
                    RTS                       ;

;-------Erases file save data.
CODE_00B2A5:        REP   #$20                ;
                    LDA.l $7F8000             ;
                    TAX                       ;
                    LDA.w $0218               ;
                    AND.w #$0003              ;
                    ASL   A                   ;
                    TAY                       ;
                    PHY                       ;
                    LDA.w $0221               ;
                    AND.w #$000F              ;
                    XBA                       ;
                    LSR   A                   ;
                    LSR   A                   ;
                    LSR   A                   ;
                    STA.b $0E                 ;
                    TAX                       ;
                    LDA.w DATA_00B34A,y       ;
                    CLC                       ;
                    ADC.b $0E                 ;
                    STA.b $00                 ;
                    LDA.w DATA_00B34A+$10,y   ;
                    STA.b $02                 ;
                    LDA.w #DATA_00B42A        ;
                    STA.b $08                 ;
                    STZ.b $04                 ;
                    LDA.l $7F8000             ;
                    TAX                       ;
                    JSR.w CODE_00B27C         ;
                    PLY                       ;
                    BEQ   +                   ;
                    CPY.b #$04                ;
                    BEQ   +                   ;
                    LDA.b $00                 ;
                    AND.w #$7FE0              ;
                    EOR.w #$0400              ;
                    STA.b $00                 ;
                    LDA.w DATA_00B34A+$18,y   ;
                    STA.b $02                 ;
                    JSR.w CODE_00B27C         ;
+                   PHY                       ;
                    LDA.w DATA_00B34A+8,y     ;
                    SEC                       ;
                    SBC.b $0E                 ;
                    STA.b $00                 ;
                    LDA.w DATA_00B34A+$10,y   ;
                    STA.b $02                 ;
                    LDA.w #DATA_00B42A        ;
                    STA.b $08                 ;
                    STZ.b $04                 ;
                    JSR.w CODE_00B27C         ;
                    PLY                       ;
                    BEQ   +                   ;
                    CPY.b #$04                ;
                    BEQ   +                   ;
                    LDA.b $00                 ;
                    AND.w #$7FE0              ;
                    EOR.w #$0400              ;
                    STA.b $00                 ;
                    LDA.w DATA_00B34A+$18,y   ;
                    STA.b $02                 ;
                    JSR.w CODE_00B27C         ;
+                   LDA.w #$FFFF              ;
                    STA.l $7F8002,x           ;
                    TXA                       ;
                    STA.l $7F8000             ;
                    SEP   #$20                ;
                    DEC.w $0221               ;
                    LDA.w $0221               ;
                    BPL   .end                ;
                    STZ.w $0221               ;
                    LDA.b #$02                ;
                    STA.b $E0                 ;
                    STZ.b $D2                 ;
                    STZ.b $1A                 ;
.end                RTL                       ;

DATA_00B34A:        db $EF,$7A,$FE,$7A,$EE,$7E,$FF,$7E ;
                    db $0F,$7B,$1E,$7B,$0E,$7F,$1F,$7F ;
                    db $16,$00,$04,$00,$16,$00,$02,$00 ;
                    db $00,$00,$12,$00,$00,$00,$14,$00 ;
                    db $BC,$B3,$A6,$B3,$90,$B3,$7A,$B3 ;
                    db $D2,$B3,$E8,$B3,$FE,$B3,$14,$B4 ;
                    db $88,$03,$89,$03,$89,$03,$89,$03 ;
                    db $89,$03,$89,$03,$89,$03,$89,$03 ;
                    db $89,$03,$89,$03,$88,$43,$8A,$03 ;
                    db $83,$03,$95,$03,$96,$03,$97,$03 ;
                    db $83,$03,$FF,$02,$FF,$02,$FF,$02 ;
                    db $FF,$02,$8A,$43,$8A,$03,$FF,$02 ;
                    db $FF,$02,$FF,$02,$98,$03,$99,$03 ;
                    db $9A,$03,$83,$03,$FF,$02,$5F,$03 ;
                    db $8A,$43,$8A,$03,$FF,$02,$FF,$02 ;
                    db $FF,$02,$FF,$02,$FF,$02,$FF,$02 ;
                    db $FF,$02,$FF,$02,$FF,$02,$8A,$43 ;
                    db $8A,$03,$FF,$02,$FF,$02,$4F,$03 ;
                    db $6F,$03,$7F,$03,$FF,$02,$FF,$02 ;
                    db $FF,$02,$FF,$02,$8A,$43,$8A,$03 ;
                    db $FF,$02,$FF,$02,$FF,$02,$FF,$02 ;
                    db $FF,$02,$FF,$02,$FF,$02,$FF,$02 ;
                    db $FF,$02,$8A,$43,$8A,$03,$FF,$02 ;
                    db $FF,$02,$FF,$02,$81,$03,$83,$03 ;
                    db $97,$03,$FF,$02,$FF,$02,$FF,$02 ;
                    db $8A,$43,$88,$83,$89,$83,$89,$83 ;
                    db $89,$83,$89,$83,$89,$83,$89,$83 ;
                    db $89,$83,$89,$83,$89,$83,$88,$C3 ;

DATA_00B42A:        db $FF,$02,$FF,$02,$FF,$02,$FF,$02 ;
                    db $FF,$02,$FF,$02,$FF,$02,$FF,$02 ;
                    db $FF,$02,$FF,$02,$FF,$02 ;

CODE_00B440:        LDA.b $F6                 ;
                    ORA.b $F7                 ;
                    AND.b #$80                ;
                    STA.b $00                 ;
                    LDA.b $F4                 ;
                    ORA.b $F5                 ;
                    AND.b #$3C                ;
                    ORA.b $00                 ;
                    BEQ   +                   ;
                    STA.b $00                 ;
                    AND.b #$2C                ;
                    BEQ   ++                  ;
                    LDA.w $0222               ;
                    EOR.b #$04                ;
                    STA.w $0222               ;
                    REP   #$20                ;
                    LDA.l $7F8000             ;
                    TAX                       ;
                    LDA.w $0218               ;
                    AND.w #$0003              ;
                    ASL   A                   ;
                    TAY                       ;
                    LDA.w DATA_00B5BA,y       ;
                    XBA                       ;
                    STA.l $7F8002,x           ;
                    LDA.w #$8006              ;
                    XBA                       ;
                    STA.l $7F8004,x           ;
                    LDA.w #$02FF              ;
                    STA.l $7F8006,x           ;
                    STA.l $7F8008,x           ;
                    STA.l $7F800A,x           ;
                    PHX                       ;
                    LDX.w $0222               ;
                    LDA.w #$034F              ;
                    STA.l $7F8006,x           ;
                    PLX                       ;
                    LDA.w #$FFFF              ;
                    STA.l $7F800C,x           ;
                    TXA                       ;
                    CLC                       ;
                    ADC.w #$000C              ;
                    STA.l $7F8000             ;
                    SEP   #$20                ;
                    LDA.b #$23                ;
                    STA.b $63                 ;
+                   JMP.w .end                ;
++                  LDA.b $00                 ;
                    AND.b #$90                ;
                    BNE   +                   ;
-                   LDA.b #$22                ;
                    STA.b $63                 ;
                    JMP.w .end                ;
+                   LDA.b #$05                ;
                    STA.b $63                 ;
                    INC.b $E0                 ;
                    LDA.w $0222               ;
                    BEQ   -                   ;
                    LDA.w $0218               ;
                    AND.b #$03                ;
                    STA.b $00                 ;
                    LDA.b $D1                 ;
                    AND.b #$03                ;
                    ASL   A                   ;
                    ASL   A                   ;
                    ADC.b $00                 ;
                    TAX                       ;
                    LDA.b #$FF                ;
                    STA.b $B0,x               ;
                    STA.b $C0,x               ;
                    LDA.b #$00                ;
                    STA.b $70,x               ;
                    JSR.w CODE_00A82C         ;
                    REP   #$20                ;
                    LDA.l $7F8000             ;
                    TAX                       ;
                    LDA.w $0218               ;
                    AND.w #$0003              ;
                    ASL   A                   ;
                    TAY                       ;
                    LDA.w DATA_00B5BA+8,y     ;
                    STA.b $00                 ;
                    LDA.w $D1                 ;
                    AND.w #$0003              ;
                    XBA                       ;
                    LSR   A                   ;
                    LSR   A                   ;
                    ADC.b $00                 ;
                    STA.b $00                 ;
                    LDA.w DATA_00B5BA+$10,y   ;
                    STA.b $02                 ;
                    STZ.b $0E                 ;
                    JSR.w CODE_00B58B         ;
                    LDA.w $0218               ;
                    AND.w #$0003              ;
                    CMP.w #$0001              ;
                    BNE   +                   ;
                    PHY                       ;
                    LDA.w #$7D60              ;
                    STA.b $00                 ;
                    LDA.w $D1                 ;
                    AND.w #$0003              ;
                    XBA                       ;
                    LSR   A                   ;
                    LSR   A                   ;
                    ADC.b $00                 ;
                    STA.b $00                 ;
                    LDA.w #$000A              ;
                    STA.b $02                 ;
                    JSR.w CODE_00B58B         ;
                    PLY                       ;
+                   LDA.w DATA_00B5BA+8,y     ;
                    STA.b $00                 ;
                    LDA.w $D1                 ;
                    AND.w #$0003              ;
                    XBA                       ;
                    LSR   A                   ;
                    LSR   A                   ;
                    ADC.w #$0020              ;
                    ADC.b $00                 ;
                    STA.b $00                 ;
                    LDA.w DATA_00B5BA+$10,y   ;
                    STA.b $02                 ;
                    JSR.w CODE_00B58B         ;
                    LDA.w $0218               ;
                    AND.w #$0003              ;
                    CMP.w #$0001              ;
                    BNE   +                   ;
                    LDA.w #$7D80              ;
                    STA.b $00                 ;
                    LDA.w $D1                 ;
                    AND.w #$0003              ;
                    XBA                       ;
                    LSR   A                   ;
                    LSR   A                   ;
                    ADC.b $00                 ;
                    STA.b $00                 ;
                    LDA.w #$000A              ;
                    STA.b $02                 ;
                    JSR.w CODE_00B58B         ;
+                   LDA.w #$FFFF              ;
                    STA.l $7F8002,x           ;
                    TXA                       ;
                    STA.l $7F8000             ;
                    SEP   #$20                ;
.end                RTL                       ;

CODE_00B58B:        PHY                       ;
                    LDA.b $00                 ;
                    XBA                       ;
                    STA.l $7F8002,x           ;
                    INX                       ;
                    INX                       ;
                    LDA.b $02                 ;
                    XBA                       ;
                    STA.l $7F8002,x           ;
                    XBA                       ;
                    LSR   A                   ;
                    AND.w #$00FF              ;
                    STA.b $04                 ;
                    INX                       ;
                    INX                       ;
-                   LDY.b $0E                 ;
                    LDA.w DATA_00B5D2,y       ;[!]
                    STA.l $7F8002,x           ;
                    INC.b $0E                 ;
                    INC.b $0E                 ;
                    INX                       ;
                    INX                       ;
                    DEC.b $04                 ;
                    BNE   -                   ;
                    PLY                       ;
                    RTS                       ;

DATA_00B5BA:        db $12,$7B,$01,$7F,$11,$7F,$02,$7B
                    db $70,$79,$7F,$79,$6F,$7D,$60,$79
                    db $0C,$00,$02,$00,$0C,$00,$0C,$00

DATA_00B5D2:        db $60,$03,$61,$03,$62,$03,$63,$03
                    db $FF,$02,$FF,$02,$70,$03,$71,$03
                    db $72,$03,$73,$03,$FF,$02,$FF,$02

DATA_00B5EA:        db $00,$01,$FF,$07,$08,$09,$0A,$7F
                    db $17,$18,$19,$1A,$7F,$07,$08,$09
                    db $0A,$0E,$17,$18,$19,$1A,$1E,$17
                    db $18,$19,$1A,$7F,$7F,$7F,$0B,$0C
                    db $0D,$07,$08,$09,$0A,$0F,$17,$18
                    db $19,$1A,$1F,$1B,$1C,$1D,$20,$1B
                    db $1C,$1D,$21,$1B,$1C,$1D,$30,$1B
                    db $1C,$1D,$31,$65,$66,$67,$75,$76
                    db $77