;-------[?]Load SRAM for SMB1?
CODE_008F03:        PHX                       ;
                    PHY                       ;
                    PHB                       ;
                    PHK                       ;
                    PLB                       ;
                    LDA.l $701FF8             ;
                    BEQ   +                   ;
                    JMP.w ++++++              ;
+                   REP   #$30                ;
                    STZ.b $00                 ;
                    LDA.l $700004             ;
                    TAX                       ;
                    SEP   #$20                ;
                    LDA.w $077A               ;
                    BEQ   ++                  ;
                    LDA.w $07FC               ;
                    CMP.w $0781               ;
                    BEQ   +                   ;
                    CMP.b #$01                ;
                    BEQ   ++                  ;
                    JMP.w ++++                ;
+                   LDA.w $075F               ;
                    CMP.w $0766               ;
                    BCC   ++++                ;
++                  LDA.w $07FC               ;
                    STA.b $02                 ;
                    CMP.l $700015,x           ;
                    BEQ   +                   ;
                    CMP.b #$01                ;
                    BEQ   +++                 ;
                    BRA   ++                  ;
+                   LDA.l $700010,x           ;
                    BMI   +++                 ;
                    CMP.w $075F               ;
                    BCC   +++                 ;
++                  LDA.l $700010,x           ;
                    JSR.w CODE_0092F6         ;
                    LDA.l $700010,x           ;
                    JSR.w CODE_0092F6         ;
                    LDA.l $700010,x           ;
                    BRA   +                   ;
+++                 LDA.w $075F               ;
                    JSR.w CODE_0092F6         ;
                    LDA.b #$00                ;
                    JSR.w CODE_0092F6         ;
                    LDA.b #$00                ;
+                   BRA   +++++               ;
++++                LDA.w $0781               ;
                    STA.b $02                 ;
                    CMP.l $700015,x           ;
                    BEQ   +                   ;
                    CMP.b #$01                ;
                    BEQ   +++                 ;
                    BRA   ++                  ;
+                   LDA.l $700010,x           ;
                    BMI   +++                 ;
                    CMP.w $0766               ;
                    BCC   +++                 ;
++                  LDA.l $700010,x           ;
                    JSR.w CODE_0092F6         ;
                    LDA.l $700010,x           ;
                    JSR.w CODE_0092F6         ;
                    LDA.l $700010,x           ;
                    BRA   +++++               ;
+++                 LDA.w $0766               ;
                    JSR.w CODE_0092F6         ;
                    LDA.w $0763               ;
                    JSR.w CODE_0092F6         ;
                    LDA.w $0767               ;
+++++               JSR.w CODE_0092F6         ;
                    LDA.w $075A               ;
                    STA.b $04                 ;
                    LDA.w $0761               ;
                    STA.b $05                 ;
                    REP   #$20                ;
                    LDA.w $0753               ;
                    AND.w #$00FF              ;
                    TAY                       ;
                    SEP   #$20                ;
                    LDA.w $04,y               ;
                    BPL   +                   ;
                    LDA.b #$04                ;
+                   JSR.w CODE_0092F6         ;
                    TYA                       ;
                    EOR.b #$01                ;
                    TAY                       ;
                    LDA.w $04,y               ;
                    BPL   +                   ;
                    LDA.b #$04                ;
+                   JSR.w CODE_0092F6         ;
                    PHX                       ;
                    JSR.w .sub                ;
                    PLX                       ;
                    LDA.l $700010,x           ;
                    ORA.b $02                 ;
                    JSR.w CODE_0092F6         ;
                    LDA.w $077A               ;
                    JSR.w CODE_0092F6         ;
                    REP   #$20                ;
                    LDA.w #$0000              ;
                    SEC                       ;
                    SBC.b $00                 ;
                    STA.l $700010,x           ;
                    SEP   #$30                ;
                    PLB                       ;
                    PLY                       ;
                    PLX                       ;
                    RTL                       ;
++++++              REP   #$30                ;
                    STZ.b $00                 ;
                    LDA.l $700004             ;
                    TAX                       ;
                    SEP   #$20                ;
                    LDA.l $701FF9             ;
                    JSR.w CODE_0092F6         ;
                    LDA.b #$00                ;
                    JSR.w CODE_0092F6         ;
                    LDA.b #$00                ;
                    JSR.w CODE_0092F6         ;
                    LDA.w $075A               ;
                    STA.b $04                 ;
                    LDA.w $0761               ;
                    STA.b $05                 ;
                    REP   #$20                ;
                    LDA.w $0753               ;
                    AND.w #$00FF              ;
                    TAY                       ;
                    SEP   #$20                ;
                    LDA.w $04,y               ;
                    BPL   +                   ;
                    LDA.b #$04                ;
+                   JSR.w CODE_0092F6         ;
                    TYA                       ;
                    EOR.b #$01                ;
                    TAY                       ;
                    LDA.w $04,y               ;
                    BPL   +                   ;
                    LDA.b #$04                ;
+                   JSR.w CODE_0092F6         ;
                    PHX                       ;
                    JSR.w .sub                ;
                    PLX                       ;
                    LDA.l $701FF8             ;
                    JSR.w CODE_0092F6         ;
                    LDA.w $077A               ;
                    JSR.w CODE_0092F6         ;
                    REP   #$20                ;
                    LDA.w #$0000              ;
                    SEC                       ;
                    SBC.b $00                 ;
                    STA.l $700010,x           ;
                    SEP   #$30                ;
                    LDA.b #$00                ;
                    STA.l $701FF8             ;
                    STA.l $701FF9             ;
                    PLB                       ;
                    PLY                       ;
                    PLX                       ;
                    RTL                       ;
.sub                PHB                       ;Push data bank
                    LDA.b #$70                ;\
                    PHA                       ; |Data bank: $70:0000
                    PLB                       ;/
                    PHD                       ;Push direct page
                    LDA.b #$07                ;\
                    XBA                       ; |Direct page: $0700
                    LDA.b #$00                ; |
                    TCD                       ;/
                    LDX.w #$0005              ;
                    SEC                       ;
-                   LDA.b $07C8,x             ;
                    SBC.w $701FE0,x           ;
                    DEX                       ;
                    BPL   -                   ;
                    BCC   +                   ;
                    INX                       ;
-                   LDA.b $07C8,x             ;
                    STA.w $701FE0,x           ;
                    INX                       ;
                    CPX.w #$0006              ;
                    BCC   -                   ;
+                   PLD                       ;
                    PLB                       ;
                    RTS                       ;

CODE_0090AC:        PHX                       ;
                    PHY                       ;
                    PHB                       ;
                    PHK                       ;
                    PLB                       ;
                    REP   #$30                ;
                    STZ.b $00                 ;
                    LDA.l $700004             ;
                    TAX                       ;
                    SEP   #$20                ;
                    LDA.l $700010,x           ;
                    BMI   ++                  ;
                    CMP.w $075F               ;
                    BCC   ++                  ;
                    BNE   +                   ;
                    LDA.l $700011,x           ;
                    CMP.w $075C               ;
                    BCC   ++                  ;
+                   LDA.l $700010,x           ;
                    JSR.w CODE_0092F6         ;
                    LDA.l $700010,x           ;
                    JSR.w CODE_0092F6         ;
                    LDA.l $700010,x           ;
                    JSR.w CODE_0092F6         ;
                    BRA   +                   ;
++                  LDA.w $075F               ;
                    JSR.w CODE_0092F6         ;
                    LDA.w $075C               ;
                    JSR.w CODE_0092F6         ;
                    LDA.w $0760               ;
                    JSR.w CODE_0092F6         ;
+                   LDA.w $075A               ;
                    BPL   +                   ;
                    LDA.b #$04                ;
+                   JSR.w CODE_0092F6         ;
                    PHX                       ;
                    JSR.w .sub                ;
                    PLX                       ;
                    LDA.w $0F2B               ;
                    JSR.w CODE_0092F6         ;
                    LDA.l $7FFB05             ;
                    JSR.w CODE_0092F6         ;
                    REP   #$20                ;
                    LDA.w #$0000              ;
                    SEC                       ;
                    SBC.b $00                 ;
                    STA.l $700010,x           ;
                    SEP   #$30                ;
                    PLB                       ;
                    PLY                       ;
                    PLX                       ;
                    RTL                       ;
.sub                PHB                       ;
                    LDA.b #$70                ;\
                    PHA                       ; |Data bank: $70:0000
                    PLB                       ;/
                    PHD                       ;
                    LDA.b #$07                ;\
                    XBA                       ; |Direct page: $0700
                    LDA.b #$00                ; |
                    TCD                       ;/
                    LDX.w #$0005              ;
                    SEC                       ;
-                   LDA.b $07C8,x             ;
                    SBC.w $701FE8,x           ;
                    DEX                       ;
                    BPL   -                   ;
                    BCC   +                   ;
                    INX                       ;
-                   LDA.b $07C8,x             ;
                    STA.w $701FE8,x           ;
                    INX                       ;
                    CPX.w #$0006              ;
                    BCC   -                   ;
+                   PLD                       ;
                    PLB                       ;
                    RTS                       ;

CODE_009152:        PHX                       ;
                    PHY                       ;
                    PHB                       ;
                    PHK                       ;
                    PLB                       ;
                    STZ.b $0F                 ;
                    LDA.w $04E8               ;
                    CMP.b #$13                ;
                    BNE   +                   ;
                    DEC.w $04E8               ;
                    INC.b $0F                 ;
+                   STZ.b $02                 ;
                    STZ.b $03                 ;
                    STZ.b $00                 ;
                    STZ.b $01                 ;
                    LDA.w $04E8               ;
-                   CMP.b #$03                ;
                    BCC   +                   ;
                    SEC                       ;
                    SBC.b #$03                ;
                    INC.b $02                 ;
                    BRA   -                   ;
+                   REP   #$10                ;
                    STA.b $03                 ;
                    LDA.l $700005             ;
                    XBA                       ;
                    LDA.l $700004             ;
                    TAX                       ;
                    LDA.b $0F                 ;
                    BNE   +++                 ;
                    LDA.l $700010,x           ;
                    BMI   +++                 ;
                    CMP.b $02                 ;
                    BEQ   +                   ;
                    BCC   +++                 ;
                    JMP.w ++                  ;
+                   LDA.l $700011,x           ;
                    CMP.b $03                 ;
                    BCC   +++                 ;
++                  LDA.l $700010,x           ;
                    JSR.w CODE_0092F6         ;
                    LDA.l $700010,x           ;
                    JSR.w CODE_0092F6         ;
                    BRA   +                   ;
+++                 LDA.b $02                 ;
                    JSR.w CODE_0092F6         ;
                    LDA.b $03                 ;
                    JSR.w CODE_0092F6         ;
+                   LDA.w $04EE               ;
                    BNE   +                   ;
                    LDA.b #$05                ;
+                   JSR.w CODE_0092F6         ;
                    LDA.w $062D               ;
                    JSR.w CODE_0092F6         ;
                    LDA.w $062E               ;
                    JSR.w CODE_0092F6         ;
                    LDA.w $062F               ;
                    JSR.w CODE_0092F6         ;
                    LDA.w $0630               ;
                    JSR.w CODE_0092F6         ;
-                   REP   #$20                ;
                    LDA.w #$0000              ;
                    SEC                       ;
                    SBC.b $00                 ;
                    STA.l $700010,x           ;
                    SEP   #$30                ;
                    LDA.b $0F                 ;
                    BEQ   +                   ;
                    INC.w $04E8               ;
+                   PLB                       ;
                    PLY                       ;
                    PLX                       ;
                    RTL                       ;

;-------[?]This doesn't seem to be called anywhere.
                    STZ.b $00                 ;
                    STZ.b $01                 ;
                    LDA.l $700010,x           ;
                    JSR.w CODE_0092F6         ;
                    LDA.l $700010,x           ;
                    JSR.w CODE_0092F6         ;
                    LDA.l $700010,x           ;
                    JSR.w CODE_0092F6         ;
                    LDA.w $062D               ;
                    JSR.w CODE_0092F6         ;
                    LDA.w $062E               ;
                    JSR.w CODE_0092F6         ;
                    LDA.w $062F               ;
                    JSR.w CODE_0092F6         ;
                    LDA.w $0630               ;
                    JSR.w CODE_0092F6         ;
                    JMP.w -                   ;

CODE_00922D:        PHX                       ;
                    PHY                       ;
                    PHB                       ;
                    PHK                       ;
                    PLB                       ;
                    REP   #$30                ;
                    LDA.b $00                 ;
                    PHA                       ;
                    STZ.b $00                 ;
                    LDA.l $700004             ;
                    TAX                       ;
                    SEP   #$20                ;
                    LDA.l $700010,x           ;
                    BPL   +                   ;
                    INC   A                   ;
                    STA.l $700010,x           ;
                    BRA   ++                  ;
+                   CMP.w $0727               ;
                    BEQ   ++                  ;
                    BCC   ++                  ;
                    JMP.w +                   ;
++                  LDA.w $0727               ;
                    STA.l $700010,x           ;
                    PHX                       ;
                    LDY.w #$0000              ;
-                   LDA.w $1D00,y             ;
                    STA.l $70004C,x           ;
                    INX                       ;
                    INY                       ;
                    CPY.w #$0080              ;
                    BCC   -                   ;
                    PLX                       ;
                    PHX                       ;
                    LDY.w #$0000              ;
-                   LDA.w $1EED,y             ;
                    STA.l $700014,x           ;
                    INX                       ;
                    INY                       ;
                    CPY.w #$0038              ;
                    BCC   -                   ;
                    PLX                       ;
                    LDA.w $072B               ;
                    STA.l $700113,x           ;
+                   PHX                       ;
                    LDY.w #$0000              ;
-                   LDA.w $1D80,y             ;
                    STA.l $7000CC,x           ;
                    INX                       ;
                    INY                       ;
                    CPY.w #$0046              ;
                    BCC   -                   ;
                    PLX                       ;
                    PHX                       ;
                    LDA.w $0736               ;
                    BPL   +                   ;
                    LDA.b #$04                ;
+                   STA.l $700012,x           ;
                    LDA.w $0737               ;
                    BPL   +                   ;
                    LDA.b #$04                ;
+                   STA.l $700013,x           ;
                    PLX                       ;
                    PHX                       ;
                    LDA.l $7E3971             ;
                    STA.l $700112,x           ;
                    LDY.w #$0104              ;
                    PLX                       ;
-                   LDA.l $700010,x           ;
                    CLC                       ;
                    ADC.b $00                 ;
                    STA.b $00                 ;
                    LDA.b #$00                ;
                    ADC.b $01                 ;
                    STA.b $01                 ;
                    INX                       ;
                    DEY                       ;
                    BNE   -                   ;
                    REP   #$20                ;
                    LDA.w #$0000              ;
                    SEC                       ;
                    SBC.b $00                 ;
                    STA.l $700010,x           ;
                    SEP   #$20                ;
                    LDA.b #$00                ;
                    STA.l $7FFF03             ;
                    SEP   #$30                ;
                    PLA                       ;
                    STA.b $01                 ;
                    PLA                       ;
                    STA.b $00                 ;
                    PLB                       ;
                    PLY                       ;
                    PLX                       ;
                    RTL                       ;

CODE_0092F6:        STA.l $700010,x           ;
                    INX                       ;
                    CLC                       ;
                    ADC.b $00                 ;
                    STA.b $00                 ;
                    LDA.b $01                 ;
                    ADC.b #$00                ;
                    STA.b $01                 ;
                    RTS                       ;